// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/salesadminpb/salesadmin.proto

package salesadminpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileBytes            [][]byte `protobuf:"bytes,2,rep,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileBytes() [][]byte {
	if m != nil {
		return m.FileBytes
	}
	return nil
}

type FileUploadRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadRequest) Reset()         { *m = FileUploadRequest{} }
func (m *FileUploadRequest) String() string { return proto.CompactTextString(m) }
func (*FileUploadRequest) ProtoMessage()    {}
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{1}
}

func (m *FileUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadRequest.Unmarshal(m, b)
}
func (m *FileUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadRequest.Marshal(b, m, deterministic)
}
func (m *FileUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadRequest.Merge(m, src)
}
func (m *FileUploadRequest) XXX_Size() int {
	return xxx_messageInfo_FileUploadRequest.Size(m)
}
func (m *FileUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadRequest proto.InternalMessageInfo

func (m *FileUploadRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type FileUploadResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadResponse) Reset()         { *m = FileUploadResponse{} }
func (m *FileUploadResponse) String() string { return proto.CompactTextString(m) }
func (*FileUploadResponse) ProtoMessage()    {}
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{2}
}

func (m *FileUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadResponse.Unmarshal(m, b)
}
func (m *FileUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadResponse.Marshal(b, m, deterministic)
}
func (m *FileUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadResponse.Merge(m, src)
}
func (m *FileUploadResponse) XXX_Size() int {
	return xxx_messageInfo_FileUploadResponse.Size(m)
}
func (m *FileUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadResponse proto.InternalMessageInfo

func (m *FileUploadResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type Order struct {
	OrderId              int32    `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerName         string   `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	ItemDescription      string   `protobuf:"bytes,3,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemPrice            float64  `protobuf:"fixed64,4,opt,name=item_price,json=itemPrice,proto3" json:"item_price,omitempty"`
	Quantity             int64    `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MerchantName         string   `protobuf:"bytes,6,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	MerchantAddress      string   `protobuf:"bytes,7,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{3}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *Order) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Order) GetItemDescription() string {
	if m != nil {
		return m.ItemDescription
	}
	return ""
}

func (m *Order) GetItemPrice() float64 {
	if m != nil {
		return m.ItemPrice
	}
	return 0
}

func (m *Order) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func (m *Order) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

type OrdersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersRequest) Reset()         { *m = OrdersRequest{} }
func (m *OrdersRequest) String() string { return proto.CompactTextString(m) }
func (*OrdersRequest) ProtoMessage()    {}
func (*OrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{4}
}

func (m *OrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersRequest.Unmarshal(m, b)
}
func (m *OrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersRequest.Marshal(b, m, deterministic)
}
func (m *OrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersRequest.Merge(m, src)
}
func (m *OrdersRequest) XXX_Size() int {
	return xxx_messageInfo_OrdersRequest.Size(m)
}
func (m *OrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersRequest proto.InternalMessageInfo

type OrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdersResponse) Reset()         { *m = OrdersResponse{} }
func (m *OrdersResponse) String() string { return proto.CompactTextString(m) }
func (*OrdersResponse) ProtoMessage()    {}
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{5}
}

func (m *OrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdersResponse.Unmarshal(m, b)
}
func (m *OrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdersResponse.Marshal(b, m, deterministic)
}
func (m *OrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersResponse.Merge(m, src)
}
func (m *OrdersResponse) XXX_Size() int {
	return xxx_messageInfo_OrdersResponse.Size(m)
}
func (m *OrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersResponse proto.InternalMessageInfo

func (m *OrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type TotalSalesRevenueRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalSalesRevenueRequest) Reset()         { *m = TotalSalesRevenueRequest{} }
func (m *TotalSalesRevenueRequest) String() string { return proto.CompactTextString(m) }
func (*TotalSalesRevenueRequest) ProtoMessage()    {}
func (*TotalSalesRevenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{6}
}

func (m *TotalSalesRevenueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalSalesRevenueRequest.Unmarshal(m, b)
}
func (m *TotalSalesRevenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalSalesRevenueRequest.Marshal(b, m, deterministic)
}
func (m *TotalSalesRevenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalSalesRevenueRequest.Merge(m, src)
}
func (m *TotalSalesRevenueRequest) XXX_Size() int {
	return xxx_messageInfo_TotalSalesRevenueRequest.Size(m)
}
func (m *TotalSalesRevenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalSalesRevenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TotalSalesRevenueRequest proto.InternalMessageInfo

type TotalSalesRevenueResponse struct {
	TotalRevenue         float64  `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalSalesRevenueResponse) Reset()         { *m = TotalSalesRevenueResponse{} }
func (m *TotalSalesRevenueResponse) String() string { return proto.CompactTextString(m) }
func (*TotalSalesRevenueResponse) ProtoMessage()    {}
func (*TotalSalesRevenueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{7}
}

func (m *TotalSalesRevenueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalSalesRevenueResponse.Unmarshal(m, b)
}
func (m *TotalSalesRevenueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalSalesRevenueResponse.Marshal(b, m, deterministic)
}
func (m *TotalSalesRevenueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalSalesRevenueResponse.Merge(m, src)
}
func (m *TotalSalesRevenueResponse) XXX_Size() int {
	return xxx_messageInfo_TotalSalesRevenueResponse.Size(m)
}
func (m *TotalSalesRevenueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalSalesRevenueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalSalesRevenueResponse proto.InternalMessageInfo

func (m *TotalSalesRevenueResponse) GetTotalRevenue() float64 {
	if m != nil {
		return m.TotalRevenue
	}
	return 0
}

func init() {
	proto.RegisterType((*File)(nil), "salesadmin.File")
	proto.RegisterType((*FileUploadRequest)(nil), "salesadmin.FileUploadRequest")
	proto.RegisterType((*FileUploadResponse)(nil), "salesadmin.FileUploadResponse")
	proto.RegisterType((*Order)(nil), "salesadmin.Order")
	proto.RegisterType((*OrdersRequest)(nil), "salesadmin.OrdersRequest")
	proto.RegisterType((*OrdersResponse)(nil), "salesadmin.OrdersResponse")
	proto.RegisterType((*TotalSalesRevenueRequest)(nil), "salesadmin.TotalSalesRevenueRequest")
	proto.RegisterType((*TotalSalesRevenueResponse)(nil), "salesadmin.TotalSalesRevenueResponse")
}

func init() { proto.RegisterFile("api/salesadminpb/salesadmin.proto", fileDescriptor_aeee1f58cbe0f938) }

var fileDescriptor_aeee1f58cbe0f938 = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xf9, 0x6a, 0x32, 0x75, 0xda, 0x66, 0x85, 0x90, 0x63, 0x54, 0x64, 0xdc, 0x22, 0xb9,
	0x12, 0x2a, 0x52, 0x38, 0x21, 0x2e, 0x24, 0x42, 0x44, 0x1c, 0xf8, 0xd0, 0x16, 0x2e, 0x5c, 0xa2,
	0x4d, 0x3c, 0x88, 0x95, 0xfc, 0xd5, 0xdd, 0x75, 0xa5, 0xfe, 0x0d, 0xfe, 0x2f, 0x12, 0xda, 0xb1,
	0x9d, 0x18, 0xda, 0xa8, 0x37, 0xcf, 0x9b, 0x37, 0xb3, 0xef, 0x3d, 0xef, 0xc2, 0x73, 0x51, 0xc8,
	0x57, 0x5a, 0x24, 0xa8, 0x45, 0x9c, 0xca, 0xac, 0x58, 0xb7, 0x8a, 0xcb, 0x42, 0xe5, 0x26, 0x67,
	0xb0, 0x43, 0xc2, 0x05, 0xf4, 0x3e, 0xc8, 0x04, 0xd9, 0x53, 0x18, 0xfd, 0x94, 0x09, 0xae, 0x32,
	0x91, 0xa2, 0xe7, 0x04, 0x4e, 0x34, 0xe2, 0x43, 0x0b, 0x7c, 0x16, 0x29, 0xb2, 0x53, 0x00, 0x6a,
	0xae, 0x6f, 0x0d, 0x6a, 0xaf, 0x13, 0x74, 0x23, 0x97, 0x13, 0x7d, 0x61, 0x81, 0xf0, 0x0d, 0x4c,
	0xec, 0x8e, 0xef, 0x45, 0x92, 0x8b, 0x98, 0xe3, 0x75, 0x89, 0xda, 0xb0, 0x73, 0xe8, 0x59, 0x06,
	0xed, 0x3a, 0x9c, 0x9d, 0x5c, 0xb6, 0x54, 0x58, 0x32, 0xa7, 0x6e, 0xf8, 0x12, 0x58, 0x7b, 0x54,
	0x17, 0x79, 0xa6, 0x91, 0x3d, 0x81, 0x81, 0x42, 0x5d, 0x26, 0x86, 0xa6, 0x87, 0xbc, 0xae, 0xc2,
	0x3f, 0x0e, 0xf4, 0xbf, 0xa8, 0x18, 0x15, 0x9b, 0xc2, 0x30, 0xb7, 0x1f, 0x2b, 0x19, 0x13, 0xa7,
	0xcf, 0x0f, 0xa8, 0xfe, 0x18, 0xb3, 0x33, 0x18, 0x6f, 0x4a, 0x6d, 0xf2, 0x14, 0x55, 0xe5, 0xa6,
	0x43, 0x6e, 0xdc, 0x06, 0x24, 0x47, 0x17, 0x70, 0x22, 0x0d, 0xa6, 0xab, 0x18, 0xf5, 0x46, 0xc9,
	0xc2, 0xc8, 0x3c, 0xf3, 0xba, 0xc4, 0x3b, 0xb6, 0xf8, 0xfb, 0x1d, 0x6c, 0xcd, 0x13, 0xb5, 0x50,
	0x72, 0x83, 0x5e, 0x2f, 0x70, 0x22, 0x87, 0x8f, 0x2c, 0xf2, 0xd5, 0x02, 0xcc, 0x87, 0xe1, 0x75,
	0x29, 0x32, 0x23, 0xcd, 0xad, 0xd7, 0x0f, 0x9c, 0xa8, 0xcb, 0xb7, 0xb5, 0x95, 0x92, 0xa2, 0xda,
	0xfc, 0x12, 0x99, 0xa9, 0xa4, 0x0c, 0x2a, 0x29, 0x0d, 0xd8, 0x48, 0xd9, 0x92, 0x44, 0x1c, 0x2b,
	0xd4, 0xda, 0x3b, 0xa8, 0xa4, 0x34, 0xf8, 0xbc, 0x82, 0xc3, 0x63, 0x18, 0x93, 0x7d, 0x5d, 0x87,
	0x1c, 0xbe, 0x85, 0xa3, 0x06, 0xa8, 0xa3, 0xbb, 0x80, 0x01, 0x05, 0xa1, 0x3d, 0x27, 0xe8, 0x46,
	0x87, 0xb3, 0x49, 0x3b, 0x78, 0xe2, 0xf2, 0x9a, 0x10, 0xfa, 0xe0, 0x7d, 0xcb, 0x8d, 0x48, 0xae,
	0x2c, 0x81, 0xe3, 0x0d, 0x66, 0x25, 0x36, 0x8b, 0xdf, 0xc1, 0xf4, 0x9e, 0x5e, 0x7d, 0xc6, 0x19,
	0x8c, 0x8d, 0x6d, 0xae, 0x54, 0xd5, 0xa0, 0x3f, 0xe0, 0x70, 0x97, 0xc0, 0x9a, 0x3c, 0xfb, 0xdd,
	0x81, 0x09, 0x4d, 0xcf, 0xed, 0xd1, 0x57, 0xa8, 0x6e, 0x6c, 0x5a, 0x9f, 0x00, 0x76, 0xff, 0x9b,
	0x9d, 0xfe, 0x7f, 0x2b, 0xfe, 0xb9, 0x42, 0xfe, 0xb3, 0x7d, 0xed, 0x4a, 0x47, 0xf8, 0x88, 0x2d,
	0xc1, 0x5d, 0xa2, 0x99, 0x27, 0x49, 0x95, 0x02, 0x9b, 0xde, 0x71, 0xdb, 0x44, 0xe5, 0xfb, 0xf7,
	0xb5, 0xb6, 0x8b, 0x10, 0x1e, 0x2f, 0xd1, 0xdc, 0xb1, 0xcc, 0xce, 0xdb, 0x53, 0xfb, 0xd2, 0xf2,
	0x5f, 0x3c, 0xc0, 0x6a, 0x8e, 0x59, 0x1c, 0xfd, 0x70, 0xdb, 0x4f, 0x73, 0x3d, 0xa0, 0x07, 0xf9,
	0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x65, 0x47, 0x45, 0xb5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SalesAdminServiceClient is the client API for SalesAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SalesAdminServiceClient interface {
	// unary rpc to upload a file to the gRPC server
	FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error)
	// unary rpc to query the server for all orders
	GetAllOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error)
	// unary rpc to query the server for the total sales revenue
	GetTotalSalesRevenue(ctx context.Context, in *TotalSalesRevenueRequest, opts ...grpc.CallOption) (*TotalSalesRevenueResponse, error)
}

type salesAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewSalesAdminServiceClient(cc *grpc.ClientConn) SalesAdminServiceClient {
	return &salesAdminServiceClient{cc}
}

func (c *salesAdminServiceClient) FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error) {
	out := new(FileUploadResponse)
	err := c.cc.Invoke(ctx, "/salesadmin.SalesAdminService/FileUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *salesAdminServiceClient) GetAllOrders(ctx context.Context, in *OrdersRequest, opts ...grpc.CallOption) (*OrdersResponse, error) {
	out := new(OrdersResponse)
	err := c.cc.Invoke(ctx, "/salesadmin.SalesAdminService/GetAllOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *salesAdminServiceClient) GetTotalSalesRevenue(ctx context.Context, in *TotalSalesRevenueRequest, opts ...grpc.CallOption) (*TotalSalesRevenueResponse, error) {
	out := new(TotalSalesRevenueResponse)
	err := c.cc.Invoke(ctx, "/salesadmin.SalesAdminService/GetTotalSalesRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesAdminServiceServer is the server API for SalesAdminService service.
type SalesAdminServiceServer interface {
	// unary rpc to upload a file to the gRPC server
	FileUpload(context.Context, *FileUploadRequest) (*FileUploadResponse, error)
	// unary rpc to query the server for all orders
	GetAllOrders(context.Context, *OrdersRequest) (*OrdersResponse, error)
	// unary rpc to query the server for the total sales revenue
	GetTotalSalesRevenue(context.Context, *TotalSalesRevenueRequest) (*TotalSalesRevenueResponse, error)
}

// UnimplementedSalesAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSalesAdminServiceServer struct {
}

func (*UnimplementedSalesAdminServiceServer) FileUpload(ctx context.Context, req *FileUploadRequest) (*FileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileUpload not implemented")
}
func (*UnimplementedSalesAdminServiceServer) GetAllOrders(ctx context.Context, req *OrdersRequest) (*OrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOrders not implemented")
}
func (*UnimplementedSalesAdminServiceServer) GetTotalSalesRevenue(ctx context.Context, req *TotalSalesRevenueRequest) (*TotalSalesRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalSalesRevenue not implemented")
}

func RegisterSalesAdminServiceServer(s *grpc.Server, srv SalesAdminServiceServer) {
	s.RegisterService(&_SalesAdminService_serviceDesc, srv)
}

func _SalesAdminService_FileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesAdminServiceServer).FileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salesadmin.SalesAdminService/FileUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesAdminServiceServer).FileUpload(ctx, req.(*FileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SalesAdminService_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesAdminServiceServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salesadmin.SalesAdminService/GetAllOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesAdminServiceServer).GetAllOrders(ctx, req.(*OrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SalesAdminService_GetTotalSalesRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalSalesRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesAdminServiceServer).GetTotalSalesRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salesadmin.SalesAdminService/GetTotalSalesRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesAdminServiceServer).GetTotalSalesRevenue(ctx, req.(*TotalSalesRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SalesAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "salesadmin.SalesAdminService",
	HandlerType: (*SalesAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileUpload",
			Handler:    _SalesAdminService_FileUpload_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _SalesAdminService_GetAllOrders_Handler,
		},
		{
			MethodName: "GetTotalSalesRevenue",
			Handler:    _SalesAdminService_GetTotalSalesRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/salesadminpb/salesadmin.proto",
}
