// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/salesadminpb/salesadmin.proto

package salesadminpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileBytes            [][]byte `protobuf:"bytes,2,rep,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetFileBytes() [][]byte {
	if m != nil {
		return m.FileBytes
	}
	return nil
}

type FileUploadRequest struct {
	File                 *File    `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadRequest) Reset()         { *m = FileUploadRequest{} }
func (m *FileUploadRequest) String() string { return proto.CompactTextString(m) }
func (*FileUploadRequest) ProtoMessage()    {}
func (*FileUploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{1}
}

func (m *FileUploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadRequest.Unmarshal(m, b)
}
func (m *FileUploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadRequest.Marshal(b, m, deterministic)
}
func (m *FileUploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadRequest.Merge(m, src)
}
func (m *FileUploadRequest) XXX_Size() int {
	return xxx_messageInfo_FileUploadRequest.Size(m)
}
func (m *FileUploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadRequest proto.InternalMessageInfo

func (m *FileUploadRequest) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

type FileUploadResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUploadResponse) Reset()         { *m = FileUploadResponse{} }
func (m *FileUploadResponse) String() string { return proto.CompactTextString(m) }
func (*FileUploadResponse) ProtoMessage()    {}
func (*FileUploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aeee1f58cbe0f938, []int{2}
}

func (m *FileUploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUploadResponse.Unmarshal(m, b)
}
func (m *FileUploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUploadResponse.Marshal(b, m, deterministic)
}
func (m *FileUploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUploadResponse.Merge(m, src)
}
func (m *FileUploadResponse) XXX_Size() int {
	return xxx_messageInfo_FileUploadResponse.Size(m)
}
func (m *FileUploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileUploadResponse proto.InternalMessageInfo

func (m *FileUploadResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*File)(nil), "salesadmin.File")
	proto.RegisterType((*FileUploadRequest)(nil), "salesadmin.FileUploadRequest")
	proto.RegisterType((*FileUploadResponse)(nil), "salesadmin.FileUploadResponse")
}

func init() { proto.RegisterFile("api/salesadminpb/salesadmin.proto", fileDescriptor_aeee1f58cbe0f938) }

var fileDescriptor_aeee1f58cbe0f938 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2f, 0x4e, 0xcc, 0x49, 0x2d, 0x4e, 0x4c, 0xc9, 0xcd, 0xcc, 0x2b, 0x48, 0x42, 0xe2, 0xe8, 0x15,
	0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x71, 0x21, 0x44, 0x94, 0x9c, 0xb8, 0x58, 0xdc, 0x32, 0x73, 0x52,
	0x85, 0xa4, 0xb9, 0x38, 0xd3, 0x32, 0x73, 0x52, 0xe3, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0x38, 0x40, 0x02, 0x7e, 0x89, 0xb9, 0xa9, 0x42, 0xb2, 0x5c, 0x5c, 0x60,
	0xc9, 0xa4, 0xca, 0x92, 0xd4, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x9e, 0x20, 0xb0, 0x72, 0x27,
	0x90, 0x80, 0x92, 0x25, 0x97, 0x20, 0xc8, 0x8c, 0xd0, 0x82, 0x9c, 0xfc, 0xc4, 0x94, 0xa0, 0xd4,
	0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x15, 0x2e, 0x16, 0x90, 0x0a, 0xb0, 0x59, 0xdc, 0x46, 0x02,
	0x7a, 0x48, 0xae, 0x00, 0x29, 0x0e, 0x02, 0xcb, 0x2a, 0xe9, 0x70, 0x09, 0x21, 0x6b, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x01, 0xeb,
	0xe6, 0x08, 0x82, 0xf2, 0x8c, 0x92, 0xb8, 0x04, 0x83, 0x41, 0xc6, 0x38, 0x82, 0x8c, 0x09, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xf2, 0xe5, 0xe2, 0x42, 0x18, 0x21, 0x24, 0x8b, 0x6e, 0x11,
	0x8a, 0xab, 0xa4, 0xe4, 0x70, 0x49, 0x43, 0x6c, 0x56, 0x62, 0x70, 0xe2, 0x8b, 0xe2, 0x41, 0x0e,
	0xbd, 0x24, 0x36, 0x70, 0x98, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x27, 0x49, 0x32, 0x5d,
	0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SalesAdminServiceClient is the client API for SalesAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SalesAdminServiceClient interface {
	FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error)
}

type salesAdminServiceClient struct {
	cc *grpc.ClientConn
}

func NewSalesAdminServiceClient(cc *grpc.ClientConn) SalesAdminServiceClient {
	return &salesAdminServiceClient{cc}
}

func (c *salesAdminServiceClient) FileUpload(ctx context.Context, in *FileUploadRequest, opts ...grpc.CallOption) (*FileUploadResponse, error) {
	out := new(FileUploadResponse)
	err := c.cc.Invoke(ctx, "/salesadmin.SalesAdminService/FileUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalesAdminServiceServer is the server API for SalesAdminService service.
type SalesAdminServiceServer interface {
	FileUpload(context.Context, *FileUploadRequest) (*FileUploadResponse, error)
}

// UnimplementedSalesAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSalesAdminServiceServer struct {
}

func (*UnimplementedSalesAdminServiceServer) FileUpload(ctx context.Context, req *FileUploadRequest) (*FileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileUpload not implemented")
}

func RegisterSalesAdminServiceServer(s *grpc.Server, srv SalesAdminServiceServer) {
	s.RegisterService(&_SalesAdminService_serviceDesc, srv)
}

func _SalesAdminService_FileUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalesAdminServiceServer).FileUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salesadmin.SalesAdminService/FileUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalesAdminServiceServer).FileUpload(ctx, req.(*FileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SalesAdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "salesadmin.SalesAdminService",
	HandlerType: (*SalesAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FileUpload",
			Handler:    _SalesAdminService_FileUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/salesadminpb/salesadmin.proto",
}
