version: "3.7"
services:
  postgres:
    image: postgres:12.1-alpine
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/postgres.cer.pem -c ssl_key_file=/var/lib/postgresql/postgres.key.pem
    environment:
      POSTGRES_USER: salesadmin
      POSTGRES_PASSWORD: salesadmin
      POSTGRES_DB: salesadmin
      POSTGRES_HOST: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ../../test/certs/postgres.cer.pem:/var/lib/postgresql/postgres.cer.pem
      - ../../test/certs/postgres.key.pem:/var/lib/postgresql/postgres.key.pem
      - ../../scripts/postgres/init-db-tables.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  godev:
    image: template/godev
    volumes:
      - ../..:/root/project
      - ../../vendor/modules:/go/pkg/mod/cache
      - ./volumes/godev/.config/fisher:/root/.config/fisher
      - ./volumes/godev/.cache/fisher:/root/.cache/fisher
      - ./volumes/godev/.local/share:/root/.local/share
      - ./volumes/godev/.config/nvim/plugged:/root/.config/nvim/plugged
    stdin_open: true
    tty: true

  certdev:
    image: template/certdev
    volumes:
      - ../../test/certs:/root/certs
      - ../../scripts/auth:/root/scripts
      - ./volumes/certdev/.config/fisher:/root/.config/fisher
      - ./volumes/certdev/.cache/fisher:/root/.cache/fisher
      - ./volumes/certdev/.local/share:/root/.local/share
      - ./volumes/certdev/.config/nvim/plugged:/root/.config/nvim/plugged
    stdin_open: true
    tty: true
