version: "3.7"
services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: salesadmin
      POSTGRES_PASSWORD: salesadmin
      POSTGRES_DB: salesadmin
      POSTGRES_HOST: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ../../scripts/postgres/init-db-tables.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  envoy:
    build:
      context: ../..
      dockerfile: ./build/envoy/Dockerfile
    image: template/envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - server

  client:
    build: 
      context: ../..
      dockerfile: ./web/salesadmin/Dockerfile
    image: template/client
    ports:
      - "4000:4000"

  server:
    build:
      context: ../..
      dockerfile: ./build/salesadmin/Dockerfile
    image: template/salesadmin
    ports:
      - target: 9090
        published: 50051
        protocol: tcp
        mode: host