apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: salesadmin
  POSTGRES_HOST: postgres
  POSTGRES_USER: salesadmin
  POSTGRES_PASSWORD: salesadmin